from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserProfileViewSet,
    UserRegistrationAPIView,
    LoginAPIView,
    LogoutAPIView,
    Setup2FAAPIView,
    Disable2FAAPIView,
    UserManagementAPIView
)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Main router for UserProfileViewSet
router = DefaultRouter()
router.register(r'', UserProfileViewSet, basename='userprofile')

# Explicit routes for other user management actions
urlpatterns = [
    # JWT Token endpoints
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # Authentication and Registration
    path('register/', UserRegistrationAPIView.as_view(), name='register'),
    path('login/', LoginAPIView.as_view(), name='login'),
    path('logout/', LogoutAPIView.as_view(), name='logout'),
    
    # 2FA Endpoints
    path('setup-2fa/', Setup2FAAPIView.as_view(), name='setup_2fa'),
    path('disable-2fa/', Disable2FAAPIView.as_view(), name='disable_2fa'),
    
    # Superuser-specific actions
    path('manage/', UserManagementAPIView.as_view(), name='user_management')
]

# Include routes generated by the DefaultRouter for user profiles
urlpatterns += [
    path('profiles/', include(router.urls)),  # Handles /api/users/profiles/
]
